name: naip_asr
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - numpy==1.26.4
      - openai-whisper==20231117
      - pandas==2.2.2
      - soundfile==0.12.1
      - transformers==4.33.3
      - huggingface-hub==0.21.4
      - whisper-timestamped==1.15.3
      - google-cloud==0.34.0
      - google-cloud-storage==2.16.0
      - cython==3.0.9
      - nemo-toolkit==1.12.0
      - torch==2.2.1
      - tqdm==4.66.2
      - audiomentations==0.35.0
     
