name: master_audio
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.10.13
  - pip:
      - audiomentations==0.36.0
      - auditok==0.2.0
      - fasttext==0.9.3
      - fsspec==2024.6.1
      - gensim==4.3.2
      - google-cloud==0.34.0
      - google-cloud-storage==2.17.0
      - huggingface-hub==0.23.4
      - librosa==0.10.2.post1
      - matplotlib==3.9.0
      - numpy==1.26.4
      - openai-whisper==20231117
      - pandas==2.2.2
      - scikit-learn==1.5.0
      - scipy==1.12.0
      - soundfile==0.12.1
      - timm==0.9.2
      - tokenizers==0.19.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.66.4
      - transformers==4.42.0
      - whisper-timestamped==1.15.4
